codecov:
  token: db3e645e-9219-4aab-8edb-2b920022e5ff
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/dist/**"
  - "**/coverage/**"
  - "**/styled-system/**"
  - "**/*.config.*"
  - "**/*.d.ts"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
